[package]
name = "pormy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
termion = "1.5.5"
log = "0.4"
#env_logger = "0.9"
log4rs = "1.0.0"
